# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      # Pass the API URL to the frontend build process
      args:
        VITE_API_BASE_URL: http://backend:8080/api
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped